apiVersion: v1
items:
- apiVersion: v1
  data:
    ca.crt: |
      -----BEGIN CERTIFICATE-----
      MIIBdzCCAR2gAwIBAgIBADAKBggqhkjOPQQDAjAjMSEwHwYDVQQDDBhrM3Mtc2Vy
      dmVyLWNhQDE3Njc0MDk4NDgwHhcNMjYwMTAzMDMxMDQ4WhcNMzYwMTAxMDMxMDQ4
      WjAjMSEwHwYDVQQDDBhrM3Mtc2VydmVyLWNhQDE3Njc0MDk4NDgwWTATBgcqhkjO
      PQIBBggqhkjOPQMBBwNCAARQ6c6bKVfIyv8KLlw/e0rN+S7pXUaaciYcG8A+gxHB
      GfDovsBpk1JTHrVPaK4LqNWRxleiu+v49DjtulnIQdFUo0IwQDAOBgNVHQ8BAf8E
      BAMCAqQwDwYDVR0TAQH/BAUwAwEB/zAdBgNVHQ4EFgQU+pdQyM2XeFSSkGZatPoW
      CNGouY4wCgYIKoZIzj0EAwIDSAAwRQIgfmT721MbK5CHbGdH3r1Qfk7sbOmlzpaQ
      0+NygLMUnywCIQD7FwD/MFWUq9l32kOo6EjZAqZWZWYWxhdLU0iwGdXEEQ==
      -----END CERTIFICATE-----
  kind: ConfigMap
  metadata:
    annotations:
      kubernetes.io/description: Contains a CA bundle that can be used to verify the
        kube-apiserver when using internal endpoints such as the internal service
        IP or kubernetes.default.svc. No other usage is guaranteed across distributions
        of Kubernetes clusters.
    creationTimestamp: "2026-01-03T03:11:45Z"
    name: kube-root-ca.crt
    namespace: cloudforet-plugin
    resourceVersion: "731"
    uid: d37abcf7-e48b-4222-b6e5-b6f3e99f9d8b
- apiVersion: v1
  data:
    application.yaml: |-
      BACKEND: KubernetesConnector
      CONNECTORS:
        KubernetesConnector:
          end_port: 50052
          headless: true
          namespace: cloudforet-plugin
          replica:
            cost_analysis.DataSource: 1
            inventory.Collector: 1
            monitoring.DataSource: 1
          start_port: 50051
        PluginConnector:
          endpoint:
            v1: grpc://plugin:50051
        RepositoryConnector:
          endpoint:
            v1: grpc://repository:50051
      HOSTNAME: supervisor.svc.cluster.local
      NAME: root
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: cloudforet
      meta.helm.sh/release-namespace: cloudforet
      spaceone.auto-deploy-flag: a01289b11b4e293aa7898bd14f545db011d1c4c931b535c2f107c6a8303b10d7
    creationTimestamp: "2026-01-03T03:12:35Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: supervisor-application-scheduler-conf
    namespace: cloudforet-plugin
    resourceVersion: "825"
    uid: a5d74f4f-c4ee-44ed-bd37-2c0841b11cf8
- apiVersion: v1
  data:
    config.yaml: |2-

      REMOTE_URL:
        - file:///opt/spaceone/supervisor/config/shared.yaml
        - file:///opt/spaceone/supervisor/config/application.yaml
      GLOBAL:
        MAX_WORKERS: 1000
        CACHES:
          default:
            backend: spaceone.core.cache.redis_cache.RedisCache
            host: localhost
            port: 6379
            db: 1
            encoding: utf-8
            socket_timeout: 10
            socket_connect_timeout: 10
        LOG:
          loggers:
            spaceone:
              handlers:
                - console
                - file
          handlers:
            file:
              type: file
              filename: /var/log/spaceone/supervisor.log
        CONNECTORS:
          IdentityConnector:
            endpoint:
              v1: grpc://identity:50051
          PluginConnector:
            endpoint:
              v1: grpc://plugin:50051
          RepositoryConnector:
            endpoint:
              v1: grpc://repository:50051
        #    KubernetesConnector:
        #        namespace: root-supervisor
        #        start_port: 50051
        #        end_port: 50052
        #        headless: true
        #        replica:
        #            inventory.collector: 4

        QUEUES:
          default_q:
            backend: spaceone.core.queue.redis_queue.RedisQueue
            host: localhost
            port: 6379
            channel: supervisor_queue

        SCHEDULERS:
          sync:
            backend: spaceone.supervisor.scheduler.sync_scheduler.SyncScheduler
            queue: default_q
            interval: 10

      #  NAME: root
      #  HOSTNAME: root-supervisor.svc.cluster.local
      #  BACKEND: KubernetesConnector
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: cloudforet
      meta.helm.sh/release-namespace: cloudforet
    creationTimestamp: "2026-01-03T03:12:35Z"
    labels:
      app.kubernetes.io/managed-by: Helm
    name: supervisor-conf
    namespace: cloudforet-plugin
    resourceVersion: "845"
    uid: 7c7a0547-cd04-4de7-bf95-6c2d3d682305
kind: List
metadata:
  resourceVersion: ""
