apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "plugin-nutanix.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "plugin-nutanix.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      {{- include "plugin-nutanix.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "plugin-nutanix.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "plugin-nutanix.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - name: grpc
          containerPort: {{ .Values.service.targetPort }}
          protocol: TCP
        
        # Environment variables
        env:
        {{- range .Values.env }}
        - name: {{ .name }}
          value: {{ .value | quote }}
        {{- end }}
        - name: IDENTITY_ENDPOINT
          value: {{ .Values.apiEndpoints.identity }}
        - name: INVENTORY_ENDPOINT
          value: {{ .Values.apiEndpoints.inventory }}
        - name: REPOSITORY_ENDPOINT
          value: {{ .Values.apiEndpoints.repository }}
        - name: COST_ENDPOINT
          value: {{ .Values.apiEndpoints.costAnalysis }}
        - name: MONITORING_ENDPOINT
          value: {{ .Values.apiEndpoints.monitoring }}
        - name: NOTIFICATION_ENDPOINT
          value: {{ .Values.apiEndpoints.notification }}
        - name: DOMAIN_ID
          value: {{ .Values.cloudforet.domainId }}
        - name: WORKSPACE_ID
          value: {{ .Values.cloudforet.workspaceId }}
        - name: PLUGIN_API_KEY
          valueFrom:
            secretKeyRef:
              name: {{ include "plugin-nutanix.fullname" . }}
              key: api-key
        
        # Resource management
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        
        # Probes
        livenessProbe:
          {{- if .Values.livenessProbe.grpc }}
          grpc:
            port: {{ .Values.livenessProbe.grpc.port }}
            service: {{ .Values.livenessProbe.grpc.service }}
          {{- end }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
        
        readinessProbe:
          {{- if .Values.readinessProbe.grpc }}
          grpc:
            port: {{ .Values.readinessProbe.grpc.port }}
            service: {{ .Values.readinessProbe.grpc.service }}
          {{- end }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
        
        # Volumes
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        {{- if .Values.persistence.enabled }}
        - name: data
          mountPath: {{ .Values.persistence.mountPath }}
        {{- end }}
      
      # Volumes
      volumes:
      - name: tmp
        emptyDir: {}
      {{- if .Values.persistence.enabled }}
      - name: data
        persistentVolumeClaim:
          claimName: {{ include "plugin-nutanix.fullname" . }}
      {{- end }}
      
      # Affinity
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
